[package]
name = "rust-lifecycle-demo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-lifecycle-demo"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
tokio = { version = "1.43", features = ["full"] }